# This is a config for E2B sandbox template.
# You can use template ID (b9zwyqxbg9y4yf3t8n1z) or template name (code-loom-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("code-loom-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("code-loom-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('code-loom-test')

team_id = "e8da40ff-e3d2-4a3f-865a-d9b8e50aea0a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "code-loom-test"
template_id = "b9zwyqxbg9y4yf3t8n1z"
